services:
  llm-pipe:
    build: .
    networks:
      - metrics-net
    environment:
      KAFKA_BOOTSTRAP_SERVERS : kafka:29092

  timescaledb:
    image: timescale/timescaledb:latest-pg17
    container_name: timescaledb
    ports:
      - "5432:5432"
    networks:
      - metrics-net
    environment:
      POSTGRES_PASSWORD : timescaledb
      POSTGRES_DB : alerts_db
      POSTGRES_USER : timescaledb

    volumes:
      - timescale_data:/var/lib/postgresql/data
    restart: always

networks:
  metrics-net:
    external: true

volumes:
  timescale_data: